use_frameworks!

platform :ios, '8.0'

target 'LibraryFoundation_Example' do
  pod 'LibraryFoundation', :path => '../'

  target 'LibraryFoundation_Tests' do
    inherit! :search_paths

    
  end
end
